var moon = document.querySelector(".moon");
var body = document.body;
var p1 = document.querySelector(".text")
var div1 = document.querySelector(".f-div")
var div2 = document.querySelector(".s-div")
var div3 = document.querySelector(".t-div")
var about = document.getElementById("about")
var skills = document.querySelector(".skills")
var sun = document.querySelector(".sun")
var div4 = document.querySelector(".xdiv")
var div5 = document.querySelector(".ydiv")
var div6 = document.querySelector(".zdiv")
var p2 = document.querySelector(".text2")
var copy = document.querySelector(".copy")
moon.addEventListener("click", ()=>{
    body.style.backgroundColor = "#1F1F1F";
    p1.style.color = "white";
    p2.style.color = "white";
    div1.style.color = "white";
    div2.style.color = "white";
    div3.style.color = "white";
    div1.style.border = "1px solid white";
    div2.style.border = "1px solid white";
    div3.style.border = "1px solid white";
    div4.style.color = "white";
    div5.style.color = "white";
    div6.style.color = "white";
    div4.style.border = "1px solid white";
    div5.style.border = "1px solid white";
    div6.style.border = "1px solid white";
    about.style.color = "white";
    skills.style.color = "white";
    moon.style.display = "none";
    sun.style.display = "block";
    sun.style.filter = "invert()";
    copy.style.color = "white";
})
sun.addEventListener("click", ()=>{
    body.style.backgroundColor = "white";
    p1.style.color = "black";
    p2.style.color = "black";
    div1.style.color = "black";
    div2.style.color = "black";
    div3.style.color = "black";
    div1.style.border = "1px solid black";
    div2.style.border = "1px solid black";
    div3.style.border = "1px solid black";
    div4.style.color = "black";
    div5.style.color = "black";
    div6.style.color = "black";
    div4.style.border = "1px solid black";
    div5.style.border = "1px solid black";
    div6.style.border = "1px solid black";
    about.style.color = "#03045E";
    skills.style.color = "#03045E";
    moon.style.display = "block";
    sun.style.display = "none";
    copy.style.color = "mediumblue";
})